name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container:
      image: qfortier/jupyter-book
    steps:
    - uses: actions/checkout@v2

    - name: Make mk
      run: |
        for file in $(find . -type f -name "*.pdf"); do
            fit=Fit
            name=$(basename $file)
            if [[ $name == td* ]] || [[ $name == tp* ]] || [[ $name == ds* ]];
            then 
              fit=FitW
            fi
            echo "<iframe src=../${name}#view=$fit&navpanes=0&statusbar=0 height=700 width=100%></iframe>" > ${file%.*}.md
        done
    - name: Build the book
      run: make build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./files/_build/html
