name: deploy-book

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container:
      image: qfortier/jb-addnote
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Download notebooks"
      run: curl -O https://raw.githubusercontent.com/fortierq/scripts/main/cours/dl_nb.py; python3 dl_nb.py ${{secrets.TOKEN}}

    - name: Add notes
      run: python /addnote.py $(pwd)/files
    
    - name: Build the book
      run: jupyter-book build files

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./files/_build/html
